import json
import os
import unittest

from bitstring import BitArray

from ovos_bus_client import Message

from hivemind_bus_client.message import HiveMessage, HiveMessageType, HiveMindBinaryPayloadType
from hivemind_bus_client.serialization import (
    get_bitstring, decode_bitstring, PROTOCOL_VERSION
)

# Path to cross-platform vectors generated by HiveMind-js/test/generate_vectors.py
_VECTORS_PATH = os.path.join(
    os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))),
    "HiveMind-js", "test", "vectors.json"
)


class TestGetBitstring(unittest.TestCase):
    """Tests for bitstring encoding."""

    def test_bus_message_uncompressed(self):
        m = Message("speak", {"utterance": "hello"})
        bs = get_bitstring(HiveMessageType.BUS, payload=m, compressed=False)
        self.assertIsNotNone(bs)
        self.assertGreater(len(bs), 0)

    def test_bus_message_compressed(self):
        m = Message("speak", {"utterance": "hello"})
        bs = get_bitstring(HiveMessageType.BUS, payload=m, compressed=True)
        self.assertIsNotNone(bs)

    def test_auto_compression(self):
        """Auto mode picks smaller of compressed/uncompressed."""
        m = Message("speak", {"utterance": "hello"})
        bs = get_bitstring(HiveMessageType.BUS, payload=m, compressed=None)
        self.assertIsNotNone(bs)

    def test_binary_payload(self):
        data = b"\x00\x01\x02\x03" * 100
        bs = get_bitstring(HiveMessageType.BINARY, payload=data,
                           binary_type=HiveMindBinaryPayloadType.RAW_AUDIO)
        self.assertIsNotNone(bs)

    def test_handshake_type(self):
        bs = get_bitstring(HiveMessageType.HANDSHAKE, payload={"type": "shake"})
        self.assertIsNotNone(bs)

    def test_versioned_adds_protocol_byte(self):
        """Versioned encoding includes an 8-bit protocol version field."""
        bs_unv = get_bitstring(HiveMessageType.BUS, payload='{"t":1}',
                               compressed=False, versioned=False)
        bs_ver = get_bitstring(HiveMessageType.BUS, payload='{"t":1}',
                               compressed=False, versioned=True)
        # Versioned should be 8 bits (1 byte) longer before padding
        self.assertGreater(len(bs_ver), len(bs_unv))


class TestDecodeBitstring(unittest.TestCase):
    """Encode-decode roundtrip tests."""

    def _roundtrip(self, hive_type, payload, compressed=False,
                   binary_type=HiveMindBinaryPayloadType.UNDEFINED,
                   hivemeta=None, versioned=False):
        """Encode then decode, return the decoded HiveMessage."""
        bs = get_bitstring(hive_type, payload=payload, compressed=compressed,
                           binary_type=binary_type, hivemeta=hivemeta,
                           versioned=versioned)
        return decode_bitstring(bs)

    # ── Per-type roundtrips ───────────────────────────────────────────────

    def test_bus_message_roundtrip(self):
        m = Message("speak", {"utterance": "hello world"})
        decoded = self._roundtrip(HiveMessageType.BUS, payload=m)
        self.assertEqual(decoded.msg_type, HiveMessageType.BUS)

    def test_bus_message_compressed_roundtrip(self):
        m = Message("speak", {"utterance": "hello world"})
        decoded = self._roundtrip(HiveMessageType.BUS, payload=m, compressed=True)
        self.assertIsInstance(decoded.payload, Message)
        self.assertEqual(decoded.payload.msg_type, "speak")

    def test_handshake_type_roundtrip(self):
        payload = {"type": "shake", "data": {}, "context": {}}
        decoded = self._roundtrip(HiveMessageType.HANDSHAKE, payload=payload)
        self.assertEqual(decoded.msg_type, HiveMessageType.HANDSHAKE)

    def test_propagate_roundtrip(self):
        decoded = self._roundtrip(HiveMessageType.PROPAGATE,
                                  payload='{"msg_type":"ping","payload":{}}')
        self.assertEqual(decoded.msg_type, HiveMessageType.PROPAGATE)

    def test_escalate_roundtrip(self):
        decoded = self._roundtrip(HiveMessageType.ESCALATE, payload='{}')
        self.assertEqual(decoded.msg_type, HiveMessageType.ESCALATE)

    def test_broadcast_roundtrip(self):
        decoded = self._roundtrip(HiveMessageType.BROADCAST,
                                  payload='{"type":"alert"}')
        self.assertEqual(decoded.msg_type, HiveMessageType.BROADCAST)

    def test_ping_roundtrip(self):
        decoded = self._roundtrip(HiveMessageType.PING,
                                  payload='{"flood_id":"abc","peer":"n1"}')
        self.assertEqual(decoded.msg_type, HiveMessageType.PING)

    def test_binary_roundtrip(self):
        data = b"\x00\x01\x02\x03\xff" * 10
        bs = get_bitstring(HiveMessageType.BINARY, payload=data,
                           binary_type=HiveMindBinaryPayloadType.RAW_AUDIO,
                           compressed=False)
        decoded = decode_bitstring(bs)
        self.assertEqual(decoded.msg_type, HiveMessageType.BINARY)
        self.assertEqual(decoded.bin_type, HiveMindBinaryPayloadType.RAW_AUDIO)
        self.assertEqual(decoded.payload, data)

    def test_all_message_types(self):
        """Every non-BINARY message type survives a roundtrip."""
        types_with_payload = [
            HiveMessageType.BUS,
            HiveMessageType.SHARED_BUS,
            HiveMessageType.BROADCAST,
            HiveMessageType.PROPAGATE,
            HiveMessageType.ESCALATE,
            HiveMessageType.HELLO,
            HiveMessageType.QUERY,
            HiveMessageType.CASCADE,
            HiveMessageType.PING,
            HiveMessageType.THIRDPRTY,
        ]
        payload = {"type": "test", "data": {}, "context": {}}
        for msg_type in types_with_payload:
            bs = get_bitstring(msg_type, payload=payload)
            decoded = decode_bitstring(bs)
            self.assertEqual(decoded.msg_type, msg_type, f"Mismatch for {msg_type}")

    # ── Binary subtypes ──────────────────────────────────────────────────

    def test_binary_all_subtypes(self):
        """Each HiveMindBinaryPayloadType roundtrips correctly."""
        data = b"\xab\xcd" * 20
        for bt in HiveMindBinaryPayloadType:
            bs = get_bitstring(HiveMessageType.BINARY, payload=data,
                               binary_type=bt, compressed=False)
            decoded = decode_bitstring(bs)
            self.assertEqual(decoded.msg_type, HiveMessageType.BINARY)
            self.assertEqual(decoded.bin_type, bt,
                             f"bin_type mismatch for {bt.name}")
            self.assertEqual(decoded.payload, data)

    # ── Versioned vs unversioned ─────────────────────────────────────────

    def test_versioned_roundtrip(self):
        m = Message("speak", {"utterance": "versioned"})
        decoded = self._roundtrip(HiveMessageType.BUS, payload=m,
                                  versioned=True)
        self.assertEqual(decoded.msg_type, HiveMessageType.BUS)
        self.assertEqual(decoded.payload.msg_type, "speak")

    def test_unversioned_roundtrip(self):
        m = Message("speak", {"utterance": "unversioned"})
        decoded = self._roundtrip(HiveMessageType.BUS, payload=m,
                                  versioned=False)
        self.assertEqual(decoded.msg_type, HiveMessageType.BUS)

    # ── Compressed vs uncompressed ───────────────────────────────────────

    def test_compressed_vs_uncompressed_decode(self):
        """Both compressed and uncompressed encode to decodable bitstrings."""
        m = Message("speak", {"utterance": "test payload"})
        for comp in (True, False):
            decoded = self._roundtrip(HiveMessageType.BUS, payload=m,
                                      compressed=comp)
            self.assertEqual(decoded.payload.msg_type, "speak")

    # ── Metadata ─────────────────────────────────────────────────────────

    def test_with_metadata(self):
        m = Message("speak", {"utterance": "hi"})
        meta = {"client_id": "test-123"}
        decoded = self._roundtrip(HiveMessageType.BUS, payload=m,
                                  hivemeta=meta)
        self.assertEqual(decoded.metadata, meta)

    def test_empty_metadata(self):
        decoded = self._roundtrip(HiveMessageType.BUS,
                                  payload='{"type":"test"}', hivemeta={})
        self.assertEqual(decoded.metadata, {})

    def test_nonempty_metadata(self):
        meta = {"key": "val", "num": 42}
        decoded = self._roundtrip(HiveMessageType.BUS,
                                  payload='{"type":"test"}', hivemeta=meta)
        self.assertEqual(decoded.metadata, meta)

    # ── Large payload ────────────────────────────────────────────────────

    def test_large_payload_roundtrip(self):
        """4KB+ payload roundtrips correctly."""
        text = "The quick brown fox " * 250  # ~5KB
        m = Message("speak", {"utterance": text})
        decoded = self._roundtrip(HiveMessageType.BUS, payload=m,
                                  compressed=True)
        self.assertEqual(decoded.payload.data["utterance"], text)

    def test_large_payload_uncompressed(self):
        text = "A" * 5000
        m = Message("speak", {"utterance": text})
        decoded = self._roundtrip(HiveMessageType.BUS, payload=m,
                                  compressed=False)
        self.assertEqual(decoded.payload.data["utterance"], text)


class TestDecodeBitstringRegressions(unittest.TestCase):
    """Regression tests for bugs fixed in _decode_bitstring_v1."""

    def test_binary_uncompressed_roundtrip(self):
        """Regression: bool(s.read(1)) was always True (checks BitStream length).
        Fix: use s.read(1).bool to read the actual bit."""
        data = b"\x00\x01\x02\x03\xff" * 100
        meta = {"utterance": "hello world", "lang": "en-us",
                "file_name": "tts_output.wav"}
        bs = get_bitstring(
            HiveMessageType.BINARY, payload=data,
            binary_type=HiveMindBinaryPayloadType.TTS_AUDIO,
            compressed=False, hivemeta=meta
        )
        decoded = decode_bitstring(bs)
        self.assertEqual(decoded.msg_type, HiveMessageType.BINARY)
        self.assertEqual(decoded.payload, data)
        self.assertEqual(decoded.metadata, meta)

    def test_non_binary_uncompressed_roundtrip(self):
        """Uncompressed BUS messages must decode without zlib errors."""
        m = Message("speak", {"utterance": "test"})
        bs = get_bitstring(HiveMessageType.BUS, payload=m, compressed=False)
        decoded = decode_bitstring(bs)
        self.assertEqual(decoded.msg_type, HiveMessageType.BUS)
        self.assertIsInstance(decoded.payload, Message)
        self.assertEqual(decoded.payload.msg_type, "speak")


class TestMycroft2Bitstring(unittest.TestCase):
    """Test mycroft2bitstring helper."""

    def test_from_message_object(self):
        from hivemind_bus_client.serialization import mycroft2bitstring
        msg = Message("speak", {"utterance": "hello"}, {"source": "test"})
        result = mycroft2bitstring(msg, compressed=False)
        self.assertTrue(len(result) > 0)

    def test_from_json_string(self):
        from hivemind_bus_client.serialization import mycroft2bitstring
        msg = Message("speak", {"utterance": "hello"})
        result = mycroft2bitstring(msg.serialize(), compressed=True)
        self.assertTrue(len(result) > 0)

    def test_roundtrip(self):
        from hivemind_bus_client.serialization import mycroft2bitstring, decode_bitstring
        msg = Message("speak", {"utterance": "roundtrip"}, {"lang": "en"})
        bitstr = mycroft2bitstring(msg, compressed=False)
        decoded = decode_bitstring(bitstr.bytes)
        self.assertEqual(decoded.msg_type, HiveMessageType.BUS)

    def test_auto_compression(self):
        """get_bitstring with compressed=None picks the smaller encoding."""
        from hivemind_bus_client.serialization import get_bitstring
        msg = Message("speak", {"utterance": "a" * 500})
        result = get_bitstring(hive_type=HiveMessageType.BUS, payload=msg, compressed=None)
        self.assertTrue(len(result) > 0)

    def test_unsupported_encode_version_raises(self):
        from hivemind_bus_client.serialization import get_bitstring
        from hivemind_bus_client.exceptions import UnsupportedProtocolVersion
        with self.assertRaises(UnsupportedProtocolVersion):
            get_bitstring(proto_version=999)

    def test_unsupported_decode_version_raises(self):
        """Craft a versioned bitstring with proto_version=99 and verify decode raises."""
        from bitstring import BitArray
        from hivemind_bus_client.serialization import decode_bitstring
        from hivemind_bus_client.exceptions import UnsupportedProtocolVersion
        s = BitArray()
        s.append('uint:1=1')       # padding marker
        s.append('uint:1=1')       # versioned=True
        s.append('uint:8=99')      # proto_version=99 (unsupported)
        s.append('uint:5=1')       # dummy hive_type
        # Pad to byte boundary
        while len(s) % 8 != 0:
            s.insert('uint:1=0', 0)
        with self.assertRaises(UnsupportedProtocolVersion):
            decode_bitstring(s.bytes)

    def test_versioned_encode_decode_roundtrip(self):
        from hivemind_bus_client.serialization import get_bitstring, decode_bitstring
        msg = Message("speak", {"utterance": "versioned"})
        bitstr = get_bitstring(hive_type=HiveMessageType.BUS, payload=msg,
                               compressed=False, versioned=True)
        decoded = decode_bitstring(bitstr.bytes)
        self.assertEqual(decoded.msg_type, HiveMessageType.BUS)


@unittest.skipUnless(os.path.isfile(_VECTORS_PATH),
                     f"vectors.json not found at {_VECTORS_PATH}")
class TestCrossPlatformVectors(unittest.TestCase):
    """Verify Python encoder/decoder against cross-platform test vectors."""

    @classmethod
    def setUpClass(cls):
        """Load vectors.json once."""
        with open(_VECTORS_PATH) as f:
            cls.vectors = json.load(f)

    # ── Legacy single bitstring vector ───────────────────────────────────

    def test_legacy_bitstring_vector(self):
        """The original single bitstring vector still matches."""
        v = self.vectors["bitstring"]
        bs = get_bitstring(
            HiveMessageType.BUS,
            payload=v["payload"],
            hivemeta=v["metadata"],
            compressed=v["compressed"],
            versioned=v["versioned"],
        )
        self.assertEqual(bs.bytes.hex(), v["expected_hex"])

    # ── Interop: encoder produces exact expected hex ─────────────────────

    def test_interop_encode_all(self):
        """Python encoder produces the exact hex from each interop vector."""
        for i, v in enumerate(self.vectors["bitstring_interop"]):
            with self.subTest(i=i, msg_type=v["msg_type"]):
                msg_type = HiveMessageType(v["msg_type"])
                kwargs = {
                    "hive_type": msg_type,
                    "hivemeta": v["metadata"],
                    "compressed": v["compressed"],
                    "versioned": v["versioned"],
                }
                if msg_type == HiveMessageType.BINARY:
                    kwargs["payload"] = bytes.fromhex(v["payload"])
                    kwargs["binary_type"] = HiveMindBinaryPayloadType(v["bin_type"])
                else:
                    kwargs["payload"] = v["payload"]

                bs = get_bitstring(**kwargs)
                self.assertEqual(
                    bs.bytes.hex(), v["expected_hex"],
                    f"Vector {i} ({v['msg_type']}): hex mismatch"
                )

    # ── Interop: decoder can decode each vector ──────────────────────────

    def test_interop_decode_all(self):
        """Python decoder successfully decodes every interop vector."""
        for i, v in enumerate(self.vectors["bitstring_interop"]):
            with self.subTest(i=i, msg_type=v["msg_type"]):
                raw = bytes.fromhex(v["expected_hex"])
                decoded = decode_bitstring(raw)
                msg_type = HiveMessageType(v["msg_type"])
                self.assertEqual(decoded.msg_type, msg_type)
                self.assertEqual(decoded.metadata, v["metadata"])

                if msg_type == HiveMessageType.BINARY:
                    self.assertEqual(decoded.payload.hex(), v["payload"])
                    self.assertEqual(decoded.bin_type,
                                     HiveMindBinaryPayloadType(v["bin_type"]))

    # ── Roundtrip: encode then decode each vector ────────────────────────

    def test_interop_roundtrip_all(self):
        """Encode from vector inputs, decode, verify fields match."""
        for i, v in enumerate(self.vectors["bitstring_interop"]):
            with self.subTest(i=i, msg_type=v["msg_type"]):
                msg_type = HiveMessageType(v["msg_type"])
                is_bin = msg_type == HiveMessageType.BINARY

                kwargs = {
                    "hive_type": msg_type,
                    "hivemeta": v["metadata"],
                    "compressed": v["compressed"],
                    "versioned": v["versioned"],
                }
                if is_bin:
                    kwargs["payload"] = bytes.fromhex(v["payload"])
                    kwargs["binary_type"] = HiveMindBinaryPayloadType(v["bin_type"])
                else:
                    kwargs["payload"] = v["payload"]

                bs = get_bitstring(**kwargs)
                decoded = decode_bitstring(bs)
                self.assertEqual(decoded.msg_type, msg_type)
                self.assertEqual(decoded.metadata, v["metadata"])

                if is_bin:
                    self.assertEqual(decoded.payload, bytes.fromhex(v["payload"]))
                else:
                    # Access internal _payload to avoid HiveMessage.payload
                    # property which may try to reconstruct nested types.
                    # We just verify the raw decoded JSON matches input.
                    expected = json.loads(v["payload"])
                    raw = decoded._payload
                    if isinstance(raw, str):
                        raw = json.loads(raw)
                    self.assertEqual(raw, expected)


if __name__ == "__main__":
    unittest.main()
