permissions:
  contents: read
  pull-requests: write

name: Repo Health

on:
  pull_request:
    branches: [dev, master]
  workflow_dispatch:

jobs:
  repo_health:
    uses: OpenVoiceOS/gh-automations/.github/workflows/repo-health.yml@5ef51f8a9e67a938b1adde466359b5309d48f5f6 # dev
    with:
      version_file: 'hivemind_bus_client/version.py'
